### ISSUE TITLE
Carbon Teething Issues

### ISSUE THREAD

**Issue by faraz** [ibm-client-engineering/solution-template#24]
# Code block spacing

## Old
![Zight 2024-03-07 at 20 04 36](https://github.com/ibm-client-engineering/solution-template/assets/95059/7e7e2661-766b-4ee4-8774-35b2b3ae30f0)

## Carbon
![Zight 2024-03-07 at 20 04 59](https://github.com/ibm-client-engineering/solution-template/assets/95059/c5c2b174-7d40-4b4d-b9ae-6c0f8b9a2083)

# Broken Bullets
## Old
![Zight 2024-03-07 at 20 06 20](https://github.com/ibm-client-engineering/solution-template/assets/95059/5fd0cbd8-9e4d-4268-b3d7-37e7aa905e3d)
![Zight 2024-03-07 at 20 06 54](https://github.com/ibm-client-engineering/solution-template/assets/95059/7da8fa31-db5e-4b3f-9312-355551289260)

## Carbon
![Zight 2024-03-07 at 20 05 50](https://github.com/ibm-client-engineering/solution-template/assets/95059/4dee7dbd-bf34-4fe5-ae38-8efb448d7d68)

![Zight 2024-03-07 at 20 07 17](https://github.com/ibm-client-engineering/solution-template/assets/95059/c68b5d2a-46e5-418f-aa0f-afa0c213988f)

**Comment by faraz** [comment]
See 
https://github.com/ibm-client-engineering/solution-filenet-aws/tree/carbon-faraz

**Comment by Sahaj-IBM** [comment]
<img width="1676" alt="Screenshot 2024-03-08 at 3 32 17 PM" src="https://github.com/ibm-client-engineering/solution-template/assets/139918147/5a5c294b-a390-4e4e-99e6-50bb670e2d52">
<img width="1588" alt="Screenshot 2024-03-08 at 3 32 31 PM" src="https://github.com/ibm-client-engineering/solution-template/assets/139918147/e9db3336-9efe-49ed-8073-c201866a9c70">

Fixed on PR: https://github.com/ibm-client-engineering/solution-template/pull/25
